name: Build on push

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/**

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
  build:
    name: Build
    needs: test
    uses: ./.github/workflows/build.yml