name: Build

on:
  workflow_call:
    inputs:
      ref:
        description: The target ref to test
        required: false
        default: ${{ github.ref }}
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          ref: ${{ inputs.ref }}
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.12.0
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Prepare output folder
        run: mkdir ./out
      - name: Copy xml file
        run: cp ./src/translation_data/japanese.xml ./out/japanese.xml
      - name: Enable problem matcher
        run: echo ::add-matcher::.github/problem_matchers/build.json
      - name: Build
        run: ../node_modules/.bin/ts-node ./build.ts
        working-directory: ./src/
      - name: Disable problem matcher
        run: echo '::remove-matcher owner=Build::'
      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: japanese
          path: ./out/