name: Build core

on:
  workflow_call: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Setup UV
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: auto
      - name: Install dependencies
        run: uv sync
        working-directory: ./scripts/
      - name: Enable problem matcher
        run: echo "::add-matcher::.github/problem_matchers/script_logger.json"
      - name: Build
        run: uv run python -m build.build
        working-directory: ./scripts/
      - name: Disable problem matcher
        run: echo "::remove-matcher owner=script_logger"
      - name: Copy xml file
        run: cp ./src/japanese.xml ./dist/japanese.xml
      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: japanese
          path: ./dist/japanese.xml
