name: Check game updates

on:
  schedule:
    - cron: '0 0 * * 4'
  workflow_dispatch:

jobs:
  check_update:
    name: Check game updates
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Setup UV
        uses: astral-sh/setup-uv@v10.2.0
        with:
          enable-cache: auto
      - name: Install dependencies
        run: uv sync
        working-directory: ./scripts/
      - name: Enable problem matcher
        run: echo "::add-matcher::.github/problem_matchers/script_logger.json"
      - name: Run script
        run: uv run python -m update_check.update_check ${LAST_TIMESTAMP}
        working-directory: ./scripts/
        env:
          GITHUB_TOKEN: ${{ github.token }}
          ACTIONS_VARIABLES_TOKEN: ${{ secrets.ACTIONS_VARIABLE_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          LAST_TIMESTAMP: ${{ vars.last_timestamp }}
      - name: Disable problem matcher
        run: echo "::remove-matcher owner=script_logger"
