name: Trigger comment action

on:
  pull_request_review:
    types:
      - submitted

jobs:
  get_data:
    name: Get event data
    if: ${{ github.event.review.state == 'changes_requested' && github.event.review.user.type != 'Bot' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get event data
        run: echo '${{ toJSON(github.event) }}' > ./event_data.json
      - name: Upload event data
        uses: actions/upload-artifact@v4.3.1
        with:
          name: event_data
          path: ./event_data.json
          retention-days: 1