name: Test on push/pull-request

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - scripts/**
      - .github/workflows/test.yml
      - .github/workflows/test_core.yml
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - scripts/**
      - .github/workflows/test.yml
      - .github/workflows/test_core.yml

jobs:
  call_test_core:
    permissions:
      contents: read
      checks: write
    uses: ./.github/workflows/test_core.yml
