name: Test core

on:
  workflow_call: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
      - name: Set up uv
        uses: astral-sh/setup-uv@v10.0.1
        with:
          enable-cache: auto
      - name: Install dependencies
        run: uv sync
        working-directory: ./scripts/
      - name: Enable problem matcher
        run: echo "::add-matcher::.github/problem_matchers/script_logger.json"
      - name: Run tests
        run: uv run python -m xmlrunner discover -s ./test -p "test_*.py" -o ./test/reports
        env:
          AVATAR_TAG_NAME: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || '' }}
        working-directory: ./scripts/
      - name: Disable problem matcher
        if: always()
        run: echo "::remove-matcher owner=script_logger"
      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v6.4.2
        with:
          report_paths: scripts/test/reports/TEST-*.xml
