name: Test

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/test.yml
  pull_request:
    types:
      - opened
      - ready_for_review
      - synchronize
    paths:
      - src/**
      - .github/workflows/test.yml

jobs:
  test_1:
    name: Check prohibited characters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.12.0
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Enable problem matcher
        run: echo ::add-matcher::.github/problem_matchers/test.json
      - name: Run test
        run: ../../node_modules/.bin/ts-node ./test_1.ts
        working-directory: ./src/tests/
  test_2:
    name: Check local strings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.12.0
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Enable problem matcher
        run: echo ::add-matcher::.github/problem_matchers/test.json
      - name: Run test
        run: ../../node_modules/.bin/ts-node ./test_2.ts
        working-directory: ./src/tests/